study_game:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information.
    You must know everthing that is relevant in context of esports
    about {topic}. 
  expected_output: >
    A deep understanding of the game {topic}
  agent: studying_agent

analyze_vul:
  description: >
    Based on the given {scout_report} and the context provided by study_game task, identify
    the key vulnerabilities in their gameplay, comps, default site setups and any player specific
    weak trait that can be exploited. Also focus on the main fragger of the opponent team so that
    he could be quickly punished for his game style.
  expected_output: >
    A full list of vulnerabilities of any type.
  agent: planning_agent

plan_attack:
  description: >
    Based on the identified vulnerabilities, craft an approach that can be used in attack phase to crush the opponent.
    Also craft a intelligent approach to deal with opponent in defense phase. Focus on the key traits
    of the player who plays a key role in the opponent team and is known for grabbing maximum
    frags. Develop a key strategy to counter him, so that full team will fell handicap after fragging the key player.

  expected_output: >
    Mention the output in 3 sections:
    1.Attack phase tactics
    2.Defense phase tactics
    3.Key player tactics
  agent: counter_planner